### PR TITLE
fixed std::string memory access error due to a corruption by curl api

### PR DESCRIPTION
**Pull request by sasmaster**
Also moved liboai.h into include directory.

### CODE REVIEW

**Comment by sasmaster** [comment]
> I'll review this today.
> 
> Be sure to ensure that the CMake config file abides by the new directory structure since you've moved `liboai.h`.

Commented out the line in CMake which attempts to copy that header into includes.

**Comment by sasmaster** [comment]
I would also suggest to make find()  json and curl lib in CMake either optional or remove as on Windows it doesn't work even that I have those libs built and points to their dirs doesn't eliminates all CMake errors as it fails to fins also some CMake generated temp files of those libs.  Probably that's not a problem for Linux as find_package works quite well there.

**Comment by D7EAD** [comment]
If I am not mistaken, I noticed that you removed the following functions from `netimpl.h` and `netimpl.cpp`:
1. `void SetOption(components::Body&& body)` and
2. `void SetBody(components::Body&& body)`

I am unsure as to why these were removed. Did they cause an issue?

**Review by D7EAD — CHANGES_REQUESTED** [review]
Changes requested:
* `liboai/core/netimpl.cpp`
   * Line 166: perform this check when assigning to `this->url_str` directly following `curl_easy_getinfo` for `CURLINFO_EFFECTIVE_URL`, and then move `this->url_str` to `liboai::Response`.
   * If functions `SetOption(Body&&)` and `SetBody(Body&&)` do not cause issues or there is no reason to remove them, please revert back to their versions found in 3.0.1.
* `liboai/include/core/response.h` and `.cpp`
   * Is the added lvalue function signature for `Response`'s constructor necessary?

**Comment by FunnyPixel** [comment]
> > > Line 166: perform this check when assigning to this->url_str directly following curl_easy_getinfo for CURLINFO_EFFECTIVE_URL, and then move this->url_str to liboai::Response.
> > > Sorry I am not sure I understand the intention. I mean I see what you want, but then what? Let's say effective_url is null,then what?
> > > The rest is fixed.
> 
> If the `char*` sent to `curl_easy_getinfo` comes out NULL, it'll likely have been due to an error with the function call and will be caught by `ErrorCheck`. However, just to be safe, we could do something along the lines of:
> 
> ```c++
> char* effectiveUrl = nullptr; 
> e[2] = curl_easy_getinfo(this->curl_, CURLINFO_EFFECTIVE_URL, &effectiveUrl);
> this->url_str = (effectiveUrl != NULL ? effectiveUrl : "");
> 
> ErrorCheck(...);
> 
> ...
> ```

NP, will modify this part tomorrow.

**Comment by D7EAD** [comment]
Alright. 

Once all requested changes have been addressed, I will gladly merge to 3.0.1, then release to main.

**Comment by FunnyPixel** [comment]
Done,you can merge

**Review by D7EAD — APPROVED** [review]

**Pull request merged**
